#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const NOTICE = "<!-- Generated by scripts/generate.mjs; edit workflow/ sources or adapter frontmatter. -->";
const CODE = String.fromCharCode(96);

function absolute(relative) { return path.join(ROOT, relative); }
function read(relative) { return fs.readFileSync(absolute(relative), "utf8").trim(); }

function adapter(relative) {
  const text = fs.readFileSync(absolute(relative), "utf8");
  if (!text.startsWith("---\n")) throw new Error(relative + " has no frontmatter");
  const closing = text.indexOf("\n---\n", 4);
  if (closing < 0) throw new Error(relative + " has unterminated frontmatter");
  if (text.slice(closing + 5).trim()) throw new Error(relative + " must contain frontmatter only");
  return text.slice(0, closing + 5).trimEnd();
}
function generated(source, body) {
  return adapter(source) + "\n\n" + NOTICE + "\n\n" + body.trim() + "\n";
}

function roleBody(role, harness) {
  let body = read("workflow/roles/" + role + ".md");
  const guidance = {
    "builder-junior": ["workflow/guidance/implementation.md", "workflow/guidance/verification.md"],
    "builder-senior": ["workflow/guidance/implementation.md", "workflow/guidance/verification.md"],
    reviewer: ["workflow/guidance/verification.md"],
  };
  for (const source of guidance[role] ?? []) body += "\n\n" + read(source);
  if (harness === "pi") {
    body += "\n\nWork only in the assigned active worktree. Preserve " +
      CODE + ".ai/work/<branch-slug>.md" + CODE + "; do not create worktrees or runtime state " +
      "elsewhere. Use one direct ordinary repository command at a time and do " +
      "not use shell chains, wrappers, interpreters, or ad hoc command programs.";
  }
  return body;
}

function openCodeCommand() {
  return [
    "Begin with the coordinator.", "", "Analyze this request:", "", "$ARGUMENTS", "",
    "Route the request through the canonical workflow generated into the " + CODE + "orchestrator" + CODE,
    "agent. The coordinator owns approvals, work state, execution delegation, combined diff",
    "inspection, and Git bookkeeping; the analyst owns problem framing, the planner owns",
    "architecture, and other role agents own bounded implementation, verification, review,",
    "and approved shipping.",
  ].join("\n");
}

function piPrompt(roles) {
  return [
    "Analyze this request:", "", "$ARGUMENTS", "",
    "You are the current main Pi session and the workflow coordinator; do not pretend that",
    "an orchestrator subagent exists. Invoke only these " + CODE + "pi-subagents" + CODE + " roles:",
    roles.join(", ") + ". Use each role's pinned model without a per-run model override.",
    "Do not delegate to any other role or allow nested delegation.",
    "",
    "For delegated command work, specify the narrowest direct repository command required.",
    "Create worktrees only under " + CODE + "<project-root>/.worktrees/" + CODE + " and keep compact state at",
    CODE + ".ai/work/<branch-slug>.md" + CODE + " in the active worktree.",
    "", read("workflow/orchestrator.md"),
  ].join("\n");
}

function codexSkill() {
  return [
    "# AI development workflow", "",
    "Use Codex collaboration agents; do not create user-owned threads for workflow roles.",
    "The main session model is selected in Codex and is not overridden by this workflow.",
    "Spawn analyst and planner with " + CODE + "gpt-5.6-sol" + CODE + "; explorer, builder-junior, and shipper",
    "with " + CODE + "gpt-5.4-mini" + CODE + "; builder-senior with " + CODE + "gpt-5.6-luna" + CODE + "; and reviewer with",
    CODE + "gpt-5.6-terra" + CODE + ". Use",
    CODE + 'fork_turns: "none"' + CODE + " or a bounded positive turn count whenever setting a model",
    "override, include all necessary context, and tell every role not to spawn subagents.",
    "",
    "Load the matching canonical brief from [roles.md](references/roles.md) for every",
    "delegation. If collaboration tools are unavailable, stop and explain that the workflow",
    "requires Codex subagents.",
    "", read("workflow/orchestrator.md"),
  ].join("\n");
}

function codexRoles(roles) {
  const sections = [
    "# Role briefs",
    "These role briefs are generated from the canonical " + CODE + "workflow/roles/" + CODE + " sources. " +
      "Append the concrete assignment, owned paths, active worktree, " + CODE + "AGENTS.md" + CODE + " " +
      "constraints, approved decisions, peer scopes, and required return evidence " +
      "whenever spawning a role.",
  ];
  for (const role of roles) {
    const title = role.replaceAll("-", " ").replace(/^\w/, (character) => character.toUpperCase());
    sections.push("## " + title, roleBody(role, "codex"));
  }
  return sections.join("\n\n") + "\n";
}

function add(result, relative, body) { result.set(relative, body); }

function outputs(manifest) {
  const result = new Map();
  for (const role of manifest.harnesses.opencode.roles) {
    add(result, "build/opencode/agents/" + role + ".md",
      generated("adapters/opencode/agents/" + role + ".md", roleBody(role, "opencode")));
  }
  add(result, "build/opencode/agents/orchestrator.md",
    generated("adapters/opencode/agents/orchestrator.md", read("workflow/orchestrator.md")));
  add(result, "build/opencode/commands/dev.md",
    generated("adapters/opencode/commands/dev.md", openCodeCommand()));
  add(result, "build/opencode/AGENTS.md", read("templates/AGENTS.global.md") + "\n");

  for (const relative of ["package.json", "package-lock.json"]) {
    add(result, "build/pi/" + relative, fs.readFileSync(absolute(relative), "utf8"));
  }
  for (const name of fs.readdirSync(absolute("pi/extensions")).sort()) {
    add(result, "build/pi/pi/extensions/" + name,
      fs.readFileSync(absolute("pi/extensions/" + name), "utf8"));
  }
  for (const role of manifest.harnesses.pi.roles) {
    add(result, "build/pi/pi/agents/" + role + ".md",
      generated("adapters/pi/agents/" + role + ".md", roleBody(role, "pi")));
  }
  add(result, "build/pi/pi/prompts/dev.md",
    generated("adapters/pi/prompts/dev.md", piPrompt(manifest.harnesses.pi.roles)));

  add(result, "build/codex/AGENTS.md", read("templates/AGENTS.global.md") + "\n");
  for (const relative of [
    "codex/.agents/plugins/marketplace.json",
    "codex/plugins/ai-dev-workflow/.codex-plugin/plugin.json",
    "codex/plugins/ai-dev-workflow/skills/dev-workflow/agents/openai.yaml",
  ]) {
    add(result, "build/" + relative, fs.readFileSync(absolute(relative), "utf8"));
  }
  add(result, "build/codex/plugins/ai-dev-workflow/skills/dev-workflow/SKILL.md",
    generated("adapters/codex/plugins/ai-dev-workflow/skills/dev-workflow/SKILL.md", codexSkill()));
  add(result, "build/codex/plugins/ai-dev-workflow/skills/dev-workflow/references/roles.md",
    NOTICE + "\n\n" + codexRoles(manifest.harnesses.codex.roles));
  return result;
}

function unexpected(result) {
  const expected = new Set(result.keys());
  const extras = [];
  for (const root of ["build/opencode", "build/codex", "build/pi/pi"]) {
    const target = absolute(root);
    if (!fs.existsSync(target)) continue;
    for (const entry of fs.readdirSync(target, { recursive: true, withFileTypes: true })) {
      if (entry.isDirectory()) continue;
      const parent = entry.parentPath ?? entry.path;
      const relative = path.relative(ROOT, path.join(parent, entry.name)).split(path.sep).join("/");
      if (!expected.has(relative)) extras.push(relative);
    }
  }
  return extras;
}

function removeOutputs() {
  for (const relative of ["build/opencode", "build/codex", "build/pi/pi"]) {
    fs.rmSync(absolute(relative), { recursive: true, force: true });
  }
  for (const relative of ["build/pi/package.json", "build/pi/package-lock.json"]) {
    fs.rmSync(absolute(relative), { force: true });
  }
}

const check = process.argv.slice(2).includes("--check");
if (process.argv.length > 3 || (process.argv.length === 3 && !check)) {
  console.error("Usage: node scripts/generate.mjs [--check]");
  process.exit(2);
}
const declared = outputs(JSON.parse(read("workflow/manifest.json")));
const stale = [];
for (const [relative, body] of declared) {
  const target = absolute(relative);
  if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== body) stale.push(relative);
}
for (const relative of ["build/opencode", "build/codex", "build/pi", "build/pi/pi"]) {
  if (!fs.existsSync(absolute(relative))) stale.push(relative);
}
const extras = unexpected(declared);
if (check) {
  if (stale.length || extras.length) {
    for (const relative of stale) console.error("STALE: " + relative);
    for (const relative of extras) console.error("UNEXPECTED: " + relative);
    console.error("Run: node scripts/generate.mjs");
    process.exit(1);
  }
  console.log("OK: checked " + declared.size + " build harness files");
} else {
  removeOutputs();
  for (const [relative, body] of declared) {
    const target = absolute(relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, body);
  }
  console.log("OK: generated " + declared.size + " build harness files");
}
