#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WORKFLOW = path.join(ROOT, "workflow");
const GENERATED_NOTICE =
  "<!-- Generated by scripts/generate.mjs; edit workflow/ sources or adapter frontmatter. -->";

function read(relative) {
  return fs.readFileSync(path.join(ROOT, relative), "utf8").trim();
}

function splitFrontmatter(relative) {
  const text = fs.readFileSync(path.join(ROOT, relative), "utf8");
  if (!text.startsWith("---\n")) {
    throw new Error(`${relative} has no frontmatter`);
  }
  const closing = text.indexOf("\n---\n", 4);
  if (closing < 0) {
    throw new Error(`${relative} has unterminated frontmatter`);
  }
  return [text.slice(0, closing + 5).trimEnd(), text.slice(closing + 5).trim()];
}

function withFrontmatter(relative, body) {
  const [frontmatter] = splitFrontmatter(relative);
  return `${frontmatter}\n\n${GENERATED_NOTICE}\n\n${body.trim()}\n`;
}

function roleBody(role, harness) {
  let body = read(`workflow/roles/${role}.md`);
  if (harness === "pi") {
    body +=
      "\n\nWork only in the assigned active worktree. Preserve " +
      "`.ai/work/<branch-slug>.md`; do not create worktrees or runtime state " +
      "elsewhere. Use one direct ordinary repository command at a time and do " +
      "not use shell chains, wrappers, interpreters, or ad hoc command programs.";
  }
  return body;
}

function openCodeCommandBody() {
  return `Begin with the coordinator.

Analyze this request:

$ARGUMENTS

Route the request through the canonical workflow generated into the \`orchestrator\`
agent. The coordinator owns approvals, work state, execution delegation, combined diff
inspection, and Git bookkeeping; the analyst owns problem framing, the planner owns
architecture, and other role agents own bounded implementation, verification, review,
and approved shipping.`;
}

function piPromptBody(roles) {
  return `Analyze this request:

$ARGUMENTS

You are the current main Pi session and the workflow coordinator; do not pretend that
an orchestrator subagent exists. Invoke only these \`pi-subagents\` roles:
${roles.join(", ")}. Do not delegate to any other role or allow nested delegation.

For delegated command work, specify the narrowest direct repository command required.
Create worktrees only under \`<project-root>/.worktrees/\` and keep compact state at
\`.ai/work/<branch-slug>.md\` in the active worktree.

${read("workflow/orchestrator.md")}`;
}

function codexSkillBody() {
  return `# AI development workflow

Use Codex collaboration agents; do not create user-owned threads for workflow roles.
Spawn analyst, planner, and reviewer with \`gpt-5.6-sol\`. Spawn explorer,
builder-junior, builder-senior, and shipper with \`gpt-5.6-terra\`. Use
\`fork_turns: "none"\` or a bounded positive turn count whenever setting a model
override, include all necessary context, and tell every role not to spawn subagents.

Load the matching canonical brief from [roles.md](references/roles.md) for every
delegation. If collaboration tools are unavailable, stop and explain that the workflow
requires Codex subagents.

${read("workflow/orchestrator.md")}`;
}

function codexRolesBody(roles) {
  const sections = [
    "# Role briefs",
    "These role briefs are generated from the canonical `workflow/roles/` sources. " +
      "Append the concrete assignment, owned paths, active worktree, `AGENTS.md` " +
      "constraints, approved decisions, peer scopes, and required return evidence " +
      "whenever spawning a role.",
  ];
  for (const role of roles) {
    const title = role.replaceAll("-", " ").replace(/^\w/, (character) =>
      character.toUpperCase(),
    );
    sections.push(`## ${title}`, read(`workflow/roles/${role}.md`));
  }
  return `${sections.join("\n\n")}\n`;
}

function expectedOutputs(manifest) {
  const outputs = new Map();
  for (const harness of ["opencode", "pi"]) {
    const root = harness === "opencode" ? ".opencode/agents" : "pi/agents";
    for (const role of manifest.harnesses[harness].roles) {
      const relative = `${root}/${role}.md`;
      outputs.set(relative, withFrontmatter(relative, roleBody(role, harness)));
    }
  }
  outputs.set(
    ".opencode/agents/orchestrator.md",
    withFrontmatter(".opencode/agents/orchestrator.md", read("workflow/orchestrator.md")),
  );
  outputs.set(
    ".opencode/commands/dev.md",
    withFrontmatter(".opencode/commands/dev.md", openCodeCommandBody()),
  );
  outputs.set(
    "pi/prompts/dev.md",
    withFrontmatter("pi/prompts/dev.md", piPromptBody(manifest.harnesses.pi.roles)),
  );
  const skill = "codex/plugins/ai-dev-workflow/skills/dev-workflow/SKILL.md";
  outputs.set(skill, withFrontmatter(skill, codexSkillBody()));
  outputs.set(
    "codex/plugins/ai-dev-workflow/skills/dev-workflow/references/roles.md",
    `${GENERATED_NOTICE}\n\n${codexRolesBody(manifest.harnesses.codex.roles)}`,
  );
  return outputs;
}

const check = process.argv.slice(2).includes("--check");
if (process.argv.length > 3 || (process.argv.length === 3 && !check)) {
  console.error("Usage: node scripts/generate.mjs [--check]");
  process.exit(2);
}

const manifest = JSON.parse(read("workflow/manifest.json"));
const outputs = expectedOutputs(manifest);
const stale = [];
for (const [relative, expected] of outputs) {
  const absolute = path.join(ROOT, relative);
  const actual = fs.existsSync(absolute) ? fs.readFileSync(absolute, "utf8") : "";
  if (actual === expected) continue;
  stale.push(relative);
  if (!check) fs.writeFileSync(absolute, expected);
}

if (check && stale.length) {
  for (const relative of stale) console.error(`STALE: ${relative}`);
  console.error("Run: node scripts/generate.mjs");
  process.exit(1);
}
console.log(`OK: ${check ? "checked" : "generated"} ${outputs.size} harness adapter files`);
