#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const NOTICE = "<!-- Generated by scripts/generate.mjs; edit canonical sources or adapter frontmatter. -->";
const CODE = String.fromCharCode(96);

function absolute(relative) { return path.join(ROOT, relative); }
function read(relative) { return fs.readFileSync(absolute(relative), "utf8").trim(); }

function adapter(relative) {
  const text = fs.readFileSync(absolute(relative), "utf8");
  if (!text.startsWith("---\n")) throw new Error(relative + " has no frontmatter");
  const closing = text.indexOf("\n---\n", 4);
  if (closing < 0) throw new Error(relative + " has unterminated frontmatter");
  if (text.slice(closing + 5).trim()) throw new Error(relative + " must contain frontmatter only");
  return text.slice(0, closing + 5).trimEnd();
}
function generated(source, body) {
  return adapter(source) + "\n\n" + NOTICE + "\n\n" + body.trim() + "\n";
}
function generatedFrom(frontmatter, body) {
  return frontmatter.trimEnd() + "\n\n" + NOTICE + "\n\n" + body.trim() + "\n";
}

const CAPABILITIES = JSON.parse(read("workflow/capabilities.json"));
const MANIFEST = JSON.parse(read("workflow/manifest.json"));

function skillFor(role) { return MANIFEST.roleSkills[role]; }
function guidancePath(name) { return "workflow/guidance/" + name + ".md"; }

function roleDescription(role) {
  return role === "orchestrator"
    ? CAPABILITIES.roles.orchestrator.description
    : MANIFEST.roles[role].description;
}

function ocExpand(commands) {
  return commands.flatMap((cmd) => [`    "${cmd}": allow`, `    "${cmd} *": allow`]);
}
function ocGit(level) {
  return CAPABILITIES.constants.git[level].flatMap((cmd) =>
    cmd === "git push"
      ? [`    "git push": ask`, `    "git push *": deny`]
      : [`    "${cmd}": allow`, `    "${cmd} *": allow`]);
}
function ocBash(role) {
  const c = CAPABILITIES.roles[role];
  if (c.shell === "none" && c.git === "none") return ["  bash: deny"];
  if (c.shell === "none") return ["  bash:", `    "*": deny`, ...ocGit(c.git),
    ...(c.worktreeLifecycle === "ask" ? ["add", "remove", "move", "prune", "repair", "lock", "unlock"]
      .flatMap((action) => [`    "git worktree ${action}": ask`, `    "git worktree ${action} *": ask`]) : [])];
  const bs = CAPABILITIES.constants.builderShell;
  const lines = ["  bash:", `    "*": ask`, ...ocExpand(bs.fileOps),
    ...bs.redirect.map((r) => `    "${r}": allow`), ...ocExpand(bs.verification), ...ocExpand(bs.dockerRead)];
  if (c.shell === "verify+integration") lines.push(...ocExpand(bs.integration));
  lines.push(`    "git *": deny`);
  for (const deny of CAPABILITIES.constants.hardDeny) lines.push(`    "${deny}": deny`, `    "${deny} *": deny`);
  return lines;
}
function ocEdit(edit) {
  if (edit === "owned") return ["  edit: allow"];
  if (edit === "work-file") return ["  edit:", `    "*": deny`, `    ".ai/work/**": allow`];
  return ["  edit: deny"];
}
function ocTask(role) {
  if (!CAPABILITIES.roles[role].delegate) return ["  task: deny"];
  const workers = Object.keys(CAPABILITIES.roles).filter((other) => other !== "orchestrator");
  return ["  task:", `    "*": deny`, ...workers.map((worker) => `    "${worker}": allow`)];
}
function ocSkill(role) {
  return ["  skill:", `    "*": deny`, `    "${skillFor(role)}": allow`];
}
function openCodeFrontmatter(role) {
  const c = CAPABILITIES.roles[role];
  const web = c.web ? "allow" : "deny";
  return [
    "---",
    "description: " + roleDescription(role),
    "mode: " + c.mode,
    "model: openai/" + c.model,
    "reasoningEffort: " + c.reasoning,
    "temperature: 0.1",
    "permission:",
    "  read:",
    `    "*": allow`,
    "  glob: allow",
    "  grep: allow",
    "  list: allow",
    ...ocEdit(c.edit),
    ...ocBash(role),
    ...ocTask(role),
    ...ocSkill(role),
    "  external_directory: deny",
    "  webfetch: " + web,
    "  websearch: " + web,
    "---",
  ].join("\n");
}

function piHasBash(c) { return c.git !== "none" || c.shell !== "none"; }
function piTools(role) {
  const c = CAPABILITIES.roles[role];
  const tools = ["read", "grep", "find", "ls"];
  if (c.web) tools.push("web_search", "fetch_content", "get_search_content");
  if (c.edit === "owned") tools.push("edit", "write");
  if (piHasBash(c)) tools.push("bash");
  return tools;
}
function piToolPerms(role) {
  const c = CAPABILITIES.roles[role];
  const lines = [`    "*": ${c.shell.startsWith("verify") ? "ask" : "deny"}`,
    "    read: allow", "    grep: allow", "    find: allow", "    ls: allow"];
  if (c.web) lines.push("    web_search: allow", "    fetch_content: allow", "    get_search_content: allow");
  if (c.edit === "owned") lines.push("    edit: allow", "    write: allow");
  if (piHasBash(c)) lines.push("    bash: allow");
  return lines;
}
function piExpand(commands) {
  return commands.flatMap((cmd) => [`    "${cmd}": allow`, `    "${cmd} *": allow`]);
}
function piGit(level) {
  const inspect = [...piExpand(["git status", "git diff", "git log"]),
    `    "git worktree list": allow`, `    "git worktree list *": allow`];
  if (level === "inspect") return inspect;
  return [...inspect,
    `    "git add": allow`, `    "git add *": allow`,
    `    "git add .": ask`, `    "git add -A": ask`, `    "git add --all": ask`,
    `    "git commit": allow`, `    "git commit *": allow`,
    `    "git commit --amend": ask`, `    "git commit --amend *": ask`,
    `    "git push": ask`, `    "git push *": ask`];
}
function piBash(role) {
  const c = CAPABILITIES.roles[role];
  if (!piHasBash(c)) return [];
  if (c.shell === "none") return ["  bash:", `    "*": deny`, ...piGit(c.git)];
  const bs = CAPABILITIES.constants.builderShell;
  const lines = ["  bash:", `    "*": ask`, ...piExpand(bs.fileOps), ...piExpand(bs.verification), ...piExpand(bs.dockerRead)];
  if (c.shell === "verify+integration") lines.push(...piExpand(bs.integration));
  lines.push(`    "git *": deny`);
  for (const deny of CAPABILITIES.constants.hardDeny) lines.push(`    "${deny} *": deny`);
  return lines;
}
function piFrontmatter(role) {
  const c = CAPABILITIES.roles[role];
  const pi = CAPABILITIES.constants.pi;
  return [
    "---",
    "name: " + role,
    "description: " + roleDescription(role),
    "model: openai/" + c.model,
    "thinking: " + c.reasoning,
    "tools: " + piTools(role).join(","),
    "permission:",
    "  tools:",
    ...piToolPerms(role),
    ...piBash(role),
    "  special:",
    "    external_directory: deny",
    "systemPromptMode: " + pi.systemPromptMode,
    "inheritProjectContext: " + pi.inheritProjectContext,
    "inheritSkills: " + pi.inheritSkills,
    "skills: " + skillFor(role),
    "skillPath: ../../skills",
    "maxSubagentDepth: " + pi.maxSubagentDepth,
    "---",
  ].join("\n");
}

function roleBody(role, harness) {
  let body = read("workflow/roles/" + role + ".md");
  const c = CAPABILITIES.roles[role];
  const docs = [];
  if (["analyst", "builder", "reviewer"].includes(role)) docs.push("code-quality");
  if (c.edit === "owned" && c.shell.startsWith("verify")) docs.push("implementation");
  if (c.shell.startsWith("verify") || c.git === "inspect") docs.push("verification");
  if (c.web) docs.push("web-use");
  for (const name of docs) body += "\n\n" + read(guidancePath(name));
  if (harness === "pi") {
    body += "\n\nWork only in the assigned active worktree. Preserve " +
      CODE + ".ai/work/<work-id>.md" + CODE + "; do not create worktrees or runtime state " +
      "elsewhere. Use one direct ordinary repository command at a time and do " +
      "not use shell chains, wrappers, interpreters, or ad hoc command programs.";
  }
  if (harness === "codex" && role === "shipper") {
    body += "\n\nIn Codex, pushing requires a network sandbox escalation even after shipping " +
      "approval. Invoke one direct " + CODE + "git push" + CODE + " command with " +
      CODE + 'sandbox_permissions: "require_escalated"' + CODE + " and a specific " +
      CODE + "justification" + CODE + " that asks the user to allow pushing the approved branch " +
      "to the approved remote. Do not retry an un-escalated push. If the escalation is declined " +
      "or the command fails, report the exact result and stop.";
  }
  return body;
}

function orchestratorBody() {
  return read("workflow/orchestrator.md");
}

function skillText(name) { return fs.readFileSync(absolute("skills/" + name + "/SKILL.md"), "utf8"); }
function skillParts(name) {
  const text = skillText(name);
  const closing = text.indexOf("\n---\n", 4);
  if (!text.startsWith("---\n") || closing < 0) throw new Error(name + " has invalid SKILL.md frontmatter");
  return { frontmatter: text.slice(0, closing + 5).trimEnd(), body: text.slice(closing + 5).trim() };
}
function copyTree(result, sourceRoot, destinationRoot) {
  const source = absolute(sourceRoot);
  for (const entry of fs.readdirSync(source, { recursive: true, withFileTypes: true })) {
    if (entry.isDirectory()) continue;
    const parent = entry.parentPath ?? entry.path;
    const relative = path.relative(source, path.join(parent, entry.name));
    add(result, path.join(destinationRoot, relative).split(path.sep).join("/"),
      fs.readFileSync(path.join(parent, entry.name), "utf8"));
  }
}

function openCodeCommand() {
  return [
    "Begin with the coordinator.", "", "Analyze this request:", "", "$ARGUMENTS", "",
    "Route the request through the canonical workflow generated into the " + CODE + "orchestrator" + CODE,
    "agent. The coordinator owns routing, approvals, work state, execution delegation, and Git",
    "bookkeeping; the designer owns unresolved product and domain choices, the analyst owns",
    "repository-specific implementation analysis, and other role agents own bounded implementation,",
    "verification, review, and approved shipping.",
  ].join("\n");
}

function piPrompt(roles) {
  return [
    "Analyze this request:", "", "$ARGUMENTS", "",
    "You are the current main Pi session and the workflow coordinator; do not pretend that",
    "an orchestrator subagent exists. Invoke only these " + CODE + "pi-subagents" + CODE + " roles:",
    roles.join(", ") + ". Use each role's pinned model and reasoning without a per-run override.",
    "Do not delegate to any other role or allow nested delegation.",
    "Before interpreting this request, load the " + CODE + skillFor("orchestrator") + CODE +
      " skill. Reload it at the beginning of every subsequent turn while this workflow remains active.",
    "If it cannot be loaded, stop instead of performing role work yourself.",
    "",
    "For delegated command work, specify the narrowest direct repository command required.",
    "Keep compact state at " + CODE + ".ai/work/<work-id>.md" + CODE + " in the active worktree.",
    "", orchestratorBody(),
  ].join("\n");
}

function oxford(items) {
  if (items.length <= 1) return items[0] ?? "";
  if (items.length === 2) return items[0] + " and " + items[1];
  return items.slice(0, -1).join(", ") + ", and " + items[items.length - 1];
}
function codexModelSentence(roles) {
  const order = [];
  const groups = new Map();
  for (const role of roles) {
    const { model, reasoning } = CAPABILITIES.roles[role];
    const key = model + "\0" + reasoning;
    if (!groups.has(key)) { groups.set(key, { model, reasoning, roles: [] }); order.push(key); }
    groups.get(key).roles.push(role);
  }
  const parts = order.map((key) => {
    const group = groups.get(key);
    return oxford(group.roles) + " with " + CODE + group.model + CODE + " at " +
      CODE + group.reasoning + CODE + " reasoning";
  });
  return "Spawn " + parts.slice(0, -1).join("; ") + "; and " + parts[parts.length - 1] + ".";
}
function codexSkillBootstrap(roles) {
  return [
    "# Codavio orchestration runtime", "",
    "Use Codex collaboration agents; do not create user-owned threads for workflow roles.",
    "The main session model is selected in Codex and is not overridden by this workflow; use " +
      CODE + CAPABILITIES.roles.orchestrator.model + CODE + " at " +
      CODE + CAPABILITIES.roles.orchestrator.reasoning + CODE + " reasoning when selecting it.",
    codexModelSentence(roles) + " Use",
    CODE + 'fork_turns: "none"' + CODE + " or a bounded positive turn count whenever setting a model or reasoning",
    "override, include all necessary context, and tell every role not to spawn subagents.",
    "",
    "Load exactly one matching role brief for each delegation:",
    ...roles.map((role) => "- " + role + ": [" + role + "](references/" + role + ".md)."),
    "",
    "If collaboration tools are unavailable, stop and explain that the workflow",
    "requires Codex subagents.",
    "",
    "Treat this workflow as active across subsequent user turns until it reaches a terminal state",
    "or the user explicitly pauses, cancels, or exits it. At the start of each such turn, reload",
    CODE + skillFor("orchestrator") + CODE + " before acting. Deviations change routing, never authority.",
  ].join("\n");
}

function codexAliasSkill() {
  return [
    "# Codavio compatibility launcher", "",
    "Immediately activate `codavio-orchestrate` with the user's complete request and follow it.",
    "Do not perform workflow work from this launcher. If `codavio-orchestrate` is unavailable, stop.",
  ].join("\n");
}

function codexSkillAgentYaml(name) {
  const title = name.replaceAll("-", " ").replace(/\b\w/g, (character) => character.toUpperCase());
  return [
    "interface:",
    `  display_name: "${title}"`,
    `  short_description: "Run ${name}"`,
    `  default_prompt: "Use $${name} for this request."`,
    "policy:",
    "  allow_implicit_invocation: false",
    "",
  ].join("\n");
}

function codexRoleBrief(role) {
  const title = role.replaceAll("-", " ").replace(/^\w/, (character) => character.toUpperCase());
  const capability = CAPABILITIES.roles[role];
  return [
    "# " + title,
    "Model assignment: `" + capability.model + "` at `" + capability.reasoning + "` reasoning.",
    "",
    "The coordinator supplies the concrete assignment, selected active worktree, exact owned paths, " +
      "applicable `AGENTS.md` constraints, referenced decisions and acceptance scenarios, peer " +
      "path boundaries, and requested return evidence. " +
      "Return the complete deliverable and evidence required by this brief, including unresolved " +
      "questions or risks.",
    "",
    roleBody(role, "codex"),
  ].join("\n") + "\n";
}

function add(result, relative, body) { result.set(relative, body); }

function outputs() {
  const result = new Map();
  for (const role of MANIFEST.harnesses.opencode.roles) {
    add(result, "build/opencode/agents/" + role + ".md",
      generatedFrom(openCodeFrontmatter(role), roleBody(role, "opencode")));
  }
  add(result, "build/opencode/agents/orchestrator.md",
    generatedFrom(openCodeFrontmatter("orchestrator"), orchestratorBody()));
  add(result, "build/opencode/commands/" + MANIFEST.command + ".md",
    generated("adapters/opencode/commands/" + MANIFEST.command + ".md", openCodeCommand()));
  for (const skill of Object.values(MANIFEST.roleSkills)) {
    copyTree(result, "skills/" + skill, "build/opencode/skills/" + skill);
  }
  add(result, "build/opencode/AGENTS.md", read("templates/AGENTS.global.md") + "\n");

  for (const relative of ["package.json", "package-lock.json"]) {
    add(result, "build/pi/" + relative, fs.readFileSync(absolute(relative), "utf8"));
  }
  for (const name of fs.readdirSync(absolute("pi/extensions")).sort()) {
    add(result, "build/pi/pi/extensions/" + name,
      fs.readFileSync(absolute("pi/extensions/" + name), "utf8"));
  }
  for (const role of MANIFEST.harnesses.pi.roles) {
    add(result, "build/pi/pi/agents/" + role + ".md",
      generatedFrom(piFrontmatter(role), roleBody(role, "pi")));
  }
  add(result, "build/pi/pi/prompts/" + MANIFEST.command + ".md",
    generated("adapters/pi/prompts/" + MANIFEST.command + ".md", piPrompt(MANIFEST.harnesses.pi.roles)));
  for (const skill of Object.values(MANIFEST.roleSkills)) {
    copyTree(result, "skills/" + skill, "build/pi/skills/" + skill);
  }

  add(result, "build/codex/AGENTS.md", read("templates/AGENTS.global.md") + "\n");
  for (const relative of [
    "codex/.agents/plugins/marketplace.json",
    "codex/plugins/codavio/.codex-plugin/plugin.json",
  ]) {
    add(result, "build/" + relative, fs.readFileSync(absolute(relative), "utf8"));
  }
  add(result, "build/codex/plugins/codavio/skills/codavio/SKILL.md",
    generated("adapters/codex/plugins/codavio/skills/codavio/SKILL.md", codexAliasSkill()));
  add(result, "build/codex/plugins/codavio/skills/codavio/agents/openai.yaml",
    fs.readFileSync(absolute("codex/plugins/codavio/skills/codavio/agents/openai.yaml"), "utf8"));
  for (const skill of Object.values(MANIFEST.roleSkills)) {
    copyTree(result, "skills/" + skill, "build/codex/plugins/codavio/skills/" + skill);
    add(result, "build/codex/plugins/codavio/skills/" + skill + "/agents/openai.yaml",
      codexSkillAgentYaml(skill));
  }
  const orchestrate = skillParts(skillFor("orchestrator"));
  add(result, "build/codex/plugins/codavio/skills/" + skillFor("orchestrator") + "/SKILL.md",
    generatedFrom(orchestrate.frontmatter,
      codexSkillBootstrap(MANIFEST.harnesses.codex.roles) + "\n\n" + orchestrate.body));
  for (const role of MANIFEST.harnesses.codex.roles) {
    add(result, "build/codex/plugins/codavio/skills/" + skillFor("orchestrator") + "/references/" + role + ".md",
      NOTICE + "\n\n" + codexRoleBrief(role));
  }
  return result;
}

function unexpected(result) {
  const expected = new Set(result.keys());
  const extras = [];
  for (const root of ["build/opencode", "build/codex", "build/pi/pi", "build/pi/skills"]) {
    const target = absolute(root);
    if (!fs.existsSync(target)) continue;
    for (const entry of fs.readdirSync(target, { recursive: true, withFileTypes: true })) {
      if (entry.isDirectory()) continue;
      const parent = entry.parentPath ?? entry.path;
      const relative = path.relative(ROOT, path.join(parent, entry.name)).split(path.sep).join("/");
      if (!expected.has(relative)) extras.push(relative);
    }
  }
  return extras;
}

function removeOutputs() {
  for (const relative of ["build/opencode", "build/codex", "build/pi/pi", "build/pi/skills"]) {
    fs.rmSync(absolute(relative), { recursive: true, force: true });
  }
  for (const relative of ["build/pi/package.json", "build/pi/package-lock.json"]) {
    fs.rmSync(absolute(relative), { force: true });
  }
}

const check = process.argv.slice(2).includes("--check");
if (process.argv.length > 3 || (process.argv.length === 3 && !check)) {
  console.error("Usage: node scripts/generate.mjs [--check]");
  process.exit(2);
}
const declared = outputs();
const stale = [];
for (const [relative, body] of declared) {
  const target = absolute(relative);
  if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== body) stale.push(relative);
}
for (const relative of ["build/opencode", "build/codex", "build/pi", "build/pi/pi"]) {
  if (!fs.existsSync(absolute(relative))) stale.push(relative);
}
const extras = unexpected(declared);
if (check) {
  if (stale.length || extras.length) {
    for (const relative of stale) console.error("STALE: " + relative);
    for (const relative of extras) console.error("UNEXPECTED: " + relative);
    console.error("Run: node scripts/generate.mjs");
    process.exit(1);
  }
  console.log("OK: checked " + declared.size + " build harness files");
} else {
  removeOutputs();
  for (const [relative, body] of declared) {
    const target = absolute(relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, body);
  }
  console.log("OK: generated " + declared.size + " build harness files");
}
